# Generated by Django 4.2.4 on 2023-10-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
