# Generated by Django 4.2.4 on 2023-10-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_chanel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='chanel_link',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
