# Generated by Django 4.2.4 on 2023-11-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_chanel_chanel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
