# Generated by Django 4.2.4 on 2023-11-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_chanel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='user',
        ),
    ]
