# Generated by Django 4.2.4 on 2023-11-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_add_chanel_username'),
        ('API', '0006_remove_chanel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.add_chanel'),
            preserve_default=False,
        ),
    ]
