# Generated by Django 4.2.4 on 2023-11-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_chanel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='user',
        ),
        migrations.AddField(
            model_name='chanel',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
