# Generated by Django 4.2.4 on 2023-11-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_chanel_chanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chanel',
            name='username',
        ),
    ]
