# Generated by Django 4.1.2 on 2023-11-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_chanel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='chanel',
        ),
    ]
