# Generated by Django 4.2.4 on 2023-11-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_chanel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_userbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_id', models.IntegerField()),
                ('api_hash', models.CharField(max_length=100)),
                ('session', models.TextField()),
            ],
        ),
    ]
