# Generated by Django 4.2.4 on 2023-11-15 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_add_userbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_userbot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
