# Generated by Django 4.2.4 on 2023-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_add_userbot_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название спонсора')),
                ('pictures', models.ImageField(upload_to='', verbose_name='Лого')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
