# Generated by Django 4.2.4 on 2023-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_add_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_userbot',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='add_userbot',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
