# Generated by Django 4.2.4 on 2023-11-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0023_pyrogramsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PyrogramSession',
        ),
    ]
