# Generated by Django 4.2.4 on 2023-12-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_delete_pyrogramsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_userbot',
            name='confirmation_code',
        ),
    ]
