# Generated by Django 4.1.2 on 2024-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_remove_add_userbot_confirmation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.TextField(verbose_name='Ответ')),
            ],
        ),
        migrations.AlterField(
            model_name='chanel',
            name='username',
            field=models.CharField(max_length=140),
        ),
    ]
