# Generated by Django 4.2.4 on 2024-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_faq_alter_chanel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
            ],
        ),
    ]
