# Generated by Django 4.1.2 on 2024-01-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_confirmation_code_phone_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmation_code',
        ),
        migrations.AddField(
            model_name='add_userbot',
            name='code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
