# Generated by Django 4.1.2 on 2024-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_delete_confirmation_code_add_userbot_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_userbot',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='add_userbot',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_userbot',
            name='session',
            field=models.TextField(blank=True),
        ),
    ]
