# Generated by Django 4.2.4 on 2024-01-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_alter_add_userbot_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_userbot',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is this userbot active?'),
        ),
    ]
