# Generated by Django 4.1.2 on 2024-02-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_chanel_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='daily_subscribers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chanel',
            name='weekly_monthy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chanel',
            name='weekly_subscribers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
