# Generated by Django 4.2.4 on 2024-02-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_chanel_daily_subscribers_chanel_weekly_monthy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='daily_subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='weekly_monthy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='weekly_subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
