# Generated by Django 4.2.4 on 2024-04-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_remove_faq_question_subjects'),
        ('API', '0035_alter_chanel_daily_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.faq_subjects'),
            preserve_default=False,
        ),
    ]
