# Generated by Django 4.2.4 on 2023-11-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_add_chanel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_chanel',
            old_name='username',
            new_name='user',
        ),
    ]
