# Generated by Django 4.2.4 on 2023-11-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_username_add_chanel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_chanel',
            old_name='user',
            new_name='username',
        ),
    ]
