# Generated by Django 4.2.4 on 2023-11-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_add_chanel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_chanel',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
