# Generated by Django 4.2.4 on 2023-11-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_advertiser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
