# Generated by Django 4.2.4 on 2023-11-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_cost_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_chanel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
