# Generated by Django 4.2.4 on 2023-11-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_chanel_description'),
        ('accounts', '0013_add_chanel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_format',
            name='chanel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.chanel'),
            preserve_default=False,
        ),
    ]
