# Generated by Django 4.2.4 on 2023-11-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cost_format_chanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost_format',
            name='chanel',
        ),
    ]
