# Generated by Django 4.1.2 on 2023-11-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_cost_format_chanel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost_format',
            old_name='add_chanel',
            new_name='add',
        ),
        migrations.AddField(
            model_name='add_chanel',
            name='cost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.cost_format'),
            preserve_default=False,
        ),
    ]
