# Generated by Django 4.1.2 on 2023-11-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_add_chanel_cost_format_add_add_chanel_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost_format',
            old_name='add',
            new_name='add_chanel',
        ),
        migrations.RemoveField(
            model_name='add_chanel',
            name='cost',
        ),
    ]
