# Generated by Django 4.2.4 on 2023-11-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_add_reklama_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_reklama',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.cost_format'),
            preserve_default=False,
        ),
    ]
