# Generated by Django 4.2.4 on 2023-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_reklama_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_reklama',
            name='status',
            field=models.CharField(choices=[('WT', 'Waiting'), ('DN', 'Done')], default='WT', max_length=2),
        ),
    ]
