# Generated by Django 4.2.4 on 2023-11-23 05:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_reklama_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+998906566970', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_advertiser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+998906566970', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
