# Generated by Django 4.2.4 on 2023-11-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_category_chanels'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_chanel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.category_chanels'),
            preserve_default=False,
        ),
    ]
