# Generated by Django 4.2.4 on 2023-12-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_add_chanel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile_advertiser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile_advertiser',
            name='last_visited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
