# Generated by Django 4.1.2 on 2024-01-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_like_profile_advertiser_like_chanel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_advertiser',
            name='like_chanel',
        ),
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile_advertiser'),
        ),
    ]
