# Generated by Django 4.1.2 on 2024-01-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_faq_alter_chanel_username'),
        ('accounts', '0038_remove_profile_advertiser_like_chanel_like_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='name',
        ),
        migrations.AddField(
            model_name='like',
            name='chanel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.chanel'),
        ),
    ]
