# Generated by Django 4.2.4 on 2024-02-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_profile_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_reklama',
            name='aprove',
            field=models.BooleanField(default=False),
        ),
    ]
