# Generated by Django 4.2.4 on 2024-02-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_add_reklama_aprove'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.add_reklama'),
            preserve_default=False,
        ),
    ]
