# Generated by Django 4.2.4 on 2024-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_faq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_reklama',
            name='order_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
