# Generated by Django 4.2.4 on 2024-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_add_reklama_commented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_reklama',
            name='commented',
            field=models.TextField(blank=True, null=True),
        ),
    ]
