# Generated by Django 4.2.4 on 2024-04-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_alter_add_reklama_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_reklama',
            name='stars_like',
            field=models.IntegerField(null=True),
        ),
    ]
