# Generated by Django 4.2.4 on 2024-04-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_add_reklama_stars_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_reklama',
            name='aprove',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
