# Generated by Django 4.2.4 on 2024-04-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_faq_subjects_faq_question_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq_question',
            name='subjects',
        ),
    ]
